### ISSUE TITLE
Fails on comments: SyntaxError: Expected "{" or [ \r\n] but "*" found.

### ISSUE THREAD

**Issue by blueyed** [vic/prefix-css#1]
I have just tried using prefix-css, but it failed as follows:

```
% prefix-css .proxy-bypass-wrapper scope.css > scope.prefixed.css

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
SyntaxError: Expected "{" or [ \r\n] but "*" found.
```

Is this an issue with node.js, or prefix-css?

I am using Ubuntu 12.04 and have installed prefix-css via npm.

**Comment by blueyed** [comment]
This appears to be caused by comments. A simple test case is the following file:

```
/* foo */
```

**Comment by vic** [comment]
@blueyed could you confirm master works for you so I can push a new release? Thanks!

**Comment by vic** [comment]
@blueyed I've actually just pushed the new version 0.0.6 to npm so you can test it, please upgrade and open another issue if you still have problems. cheers !

**Comment by blueyed** [comment]
Thanks for the fast response!

I have not verified it being fixed, but went the scss route instead to generate the prefixed CSS.
