### ISSUE TITLE
New lines after commas cause SyntaxError

### ISSUE THREAD

**Issue by pfgray** [vic/prefix-css#2]
It seems like there is an error in the parser for some css formats.

for example:

```
.test,
.test_other{
    background-color:white;
}
```

doesn't work, giving: `SyntaxError: Expected [^@,{}\n\r] but "\n" found.`
but:

```
.test, .test_other{
    background-color:white;
}
```

does work.

**Comment by vic** [comment]
@pfgray just pushed a new version with this fixed. thanks :)
